RD-3168 lock db tables on restore (#3257)
* RD-3168 LOCK some of the DB tables on restore

... otherwise in the cluster environment there might be some deadlocks
happening, similar to this one:

```
ERROR:  deadlock detected
DETAIL:  Process 14138 waits for AccessExclusiveLock on relation 17947
of database 16389; blocked by process 13110.
        Process 13110 waits for AccessShareLock on relation 18045 of
database 16389; blocked by process 14138.
        Process 14138: TRUNCATE maintenance_mode CASCADE;
        Process 13110: SELECT execution_schedules._storage_id AS
execution_schedules__storage_id...
```

We avoid this in AIO environment by stopping some services, but in case
of cluster it's not possible to stop those services on another nodes.
Hence the lock.

* Pause cloudify-api when restoring snapshots

... because it uses the DB too